// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     DetalleDeArticulo.avsc
 */
package ArticuloEvent

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullLoteTypeEnum int

const (
	UnionNullLoteTypeEnumLote UnionNullLoteTypeEnum = 1
)

type UnionNullLote struct {
	Null      *types.NullVal
	Lote      Lote
	UnionType UnionNullLoteTypeEnum
}

func writeUnionNullLote(r *UnionNullLote, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullLoteTypeEnumLote:
		return writeLote(r.Lote, w)
	}
	return fmt.Errorf("invalid value for *UnionNullLote")
}

func NewUnionNullLote() *UnionNullLote {
	return &UnionNullLote{}
}

func (r *UnionNullLote) Serialize(w io.Writer) error {
	return writeUnionNullLote(r, w)
}

func DeserializeUnionNullLote(r io.Reader) (*UnionNullLote, error) {
	t := NewUnionNullLote()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullLoteFromSchema(r io.Reader, schema string) (*UnionNullLote, error) {
	t := NewUnionNullLote()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullLote) Schema() string {
	return "[\"null\",{\"fields\":[{\"default\":null,\"name\":\"Codigo\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"LoteDeFabricante\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"LoteSecundario\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"FechaDeVencimiento\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"OtrosDatos\",\"type\":[\"null\",{\"fields\":[{\"default\":null,\"name\":\"Meta\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"Contenido\",\"type\":[\"null\",\"string\"]}],\"name\":\"Metadato\",\"type\":\"record\"}]}],\"name\":\"Lote\",\"type\":\"record\"}]"
}

func (_ *UnionNullLote) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullLote) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullLote) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullLote) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullLote) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullLote) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullLote) SetLong(v int64) {

	r.UnionType = (UnionNullLoteTypeEnum)(v)
}

func (r *UnionNullLote) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.Lote = NewLote()
		return &types.Record{Target: (&r.Lote)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullLote) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullLote) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionNullLote) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullLote) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullLote) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullLote) Finalize()                        {}

func (r *UnionNullLote) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullLoteTypeEnumLote:
		return json.Marshal(map[string]interface{}{"Andreani.EventoWhArticulos.Events.Record.Lote": r.Lote})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullLote")
}

func (r *UnionNullLote) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["Andreani.EventoWhArticulos.Events.Record.Lote"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.Lote)
	}
	return fmt.Errorf("invalid value for *UnionNullLote")
}
